#!/bin/bash
# radsecproxy daemon
# chkconfig: 2345 90 20
# description: radsecproxy daemon
# processname: radsecproxy

DAEMON_PATH="/usr/bin/"

#DAEMON=radsecproxy
DAEMON=/usr/local/sbin/radsecproxy
DAEMONOPTS="-c /etc/radsecproxy.conf -i /var/run/radsecproxy.pid"

NAME=radsecproxy
DESC="RadSec"
PIDFILE=/var/run/$NAME.pid
#SCRIPTNAME=/etc/init.d/radsec.sh
SCRIPTNAME=/etc/init.d/radsecproxy

case "$1" in
start)
        printf "%-50s" "Starting $NAME..."
        cd $DAEMON_PATH
        #PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
        $DAEMON $DAEMONOPTS
        #PID=`ps aux | grep radsec | grep -v grep | awk '{print $2}'`
        PID=`cat $PIDFILE`
        #echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            #echo $PID >> $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            #kill -HUP $PID
            kill $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
        $0 stop
        $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac